PRAGMA foreign_keys = ON;

-- 第一版「妙想」每日问题题库
-- 共 108 道。
-- 使用 INSERT OR IGNORE，重复执行不会产生重复题目。

INSERT OR IGNORE INTO idea_questions (
  id,
  question_text,
  category,
  form,
  intimacy_level,
  tags,
  enabled
) VALUES
  ('idea-q-001', '你觉得我们两个人相处时，最自然、最不用费力的一件事是什么？', 'relationship', 'describe', 2, '["relationship","describe"]', 1),
  ('idea-q-002', '回想一次你觉得“我们真的很像一对搭档”的时刻，那天发生了什么？', 'relationship', 'recall', 4, '["relationship","recall"]', 1),
  ('idea-q-003', '如果要向一个不了解我们的人解释我们为什么合得来，你会怎么说？', 'relationship', 'explain', 4, '["relationship","explain"]', 1),
  ('idea-q-004', '你觉得我们刚认识时和现在相比，最大的变化是什么？', 'relationship', 'compare', 4, '["relationship","compare"]', 1),
  ('idea-q-005', '如果把我们的关系比作一种天气、一种季节或一种风景，你会选什么？为什么？', 'relationship', 'imagine', 2, '["relationship","imagine"]', 1),
  ('idea-q-006', '如果要给我们安排一个最适合最近状态的小约会，你会推荐做什么？', 'relationship', 'recommend', 2, '["relationship","recommend"]', 1),
  ('idea-q-007', '在“被理解、被陪伴、被支持、被逗笑”里，你最近最希望从我这里得到哪一种？', 'relationship', 'choose', 5, '["relationship","choose"]', 1),
  ('idea-q-008', '你觉得一年后的我们，最可能养成一个什么新的共同习惯？', 'relationship', 'predict', 3, '["relationship","predict"]', 1),
  ('idea-q-009', '如果以后我们在一件很重要的事情上长期意见不同，你希望我们用什么方式处理？', 'relationship', 'hypothetical', 5, '["relationship","hypothetical"]', 1),
  ('idea-q-010', '你觉得一段让你安心的亲密关系，最重要的三个特点是什么？', 'relationship', 'describe', 5, '["relationship","describe"]', 1),
  ('idea-q-011', '最近有哪些很小的日常瞬间，会让你突然觉得生活还不错？', 'daily_life', 'describe', 1, '["daily_life","describe"]', 1),
  ('idea-q-012', '最近一次你过得特别舒服的一天，是怎么度过的？', 'daily_life', 'recall', 3, '["daily_life","recall"]', 1),
  ('idea-q-013', '如果明天突然多出三个完全不用工作的小时，你最想怎么用？', 'daily_life', 'imagine', 3, '["daily_life","imagine"]', 1),
  ('idea-q-014', '你更喜欢提前把一天安排好，还是当天看心情决定？为什么？', 'daily_life', 'compare', 1, '["daily_life","compare"]', 1),
  ('idea-q-015', '最近有什么很普通但很好用的小东西，想推荐给我？', 'daily_life', 'recommend', 1, '["daily_life","recommend"]', 1),
  ('idea-q-016', '你觉得自己在累的时候，最需要怎样的休息才是真的恢复？', 'daily_life', 'explain', 4, '["daily_life","explain"]', 1),
  ('idea-q-017', '如果周末只能选一项：宅家、逛街、散步、短途出门，你现在会选哪个？', 'daily_life', 'choose', 2, '["daily_life","choose"]', 1),
  ('idea-q-018', '你觉得我们以后一起生活，最容易形成什么奇怪但可爱的日常习惯？', 'daily_life', 'predict', 2, '["daily_life","predict"]', 1),
  ('idea-q-019', '如果我们有一个完全不用考虑效率的星期天，你希望它从早到晚是什么样？', 'daily_life', 'hypothetical', 3, '["daily_life","hypothetical"]', 1),
  ('idea-q-020', '最近哪一种情绪出现得最频繁？你觉得它在提醒你什么？', 'emotion', 'describe', 4, '["emotion","describe"]', 1),
  ('idea-q-021', '最近一次你被一个很小的事情治愈，是因为什么？', 'emotion', 'recall', 2, '["emotion","recall"]', 1),
  ('idea-q-022', '当你心情不好时，你更希望别人主动靠近，还是给你一点空间？为什么？', 'emotion', 'explain', 5, '["emotion","explain"]', 1),
  ('idea-q-023', '你觉得自己表达开心和表达难过时，哪一种更容易？', 'emotion', 'compare', 3, '["emotion","compare"]', 1),
  ('idea-q-024', '如果我要在你低落的时候哄你，你最推荐我做哪件小事？', 'emotion', 'recommend', 2, '["emotion","recommend"]', 1),
  ('idea-q-025', '在“说出来、被抱抱、独处、做点别的转移注意”里，你难受时最需要哪一种？', 'emotion', 'choose', 4, '["emotion","choose"]', 1),
  ('idea-q-026', '如果情绪可以变成一个房间，你最近的房间会是什么样子？', 'emotion', 'imagine', 3, '["emotion","imagine"]', 1),
  ('idea-q-027', '你觉得未来的自己会比现在更擅长处理哪一种情绪？', 'emotion', 'predict', 4, '["emotion","predict"]', 1),
  ('idea-q-028', '如果有一种情绪你希望我以后能更早察觉，你希望是哪一种？', 'emotion', 'hypothetical', 5, '["emotion","hypothetical"]', 1),
  ('idea-q-029', '小时候有没有一种味道、声音或天气，一出现就会让你立刻想起某段记忆？', 'memory', 'recall', 1, '["memory","recall"]', 1),
  ('idea-q-030', '你记忆里最有“夏天感”的一个画面是什么？', 'memory', 'describe', 3, '["memory","describe"]', 1),
  ('idea-q-031', '有没有一件当时觉得很普通、现在回头看却很珍贵的小事？', 'memory', 'recall', 3, '["memory","recall"]', 1),
  ('idea-q-032', '小时候的你和现在的你，最像的地方是什么？最不一样的地方呢？', 'memory', 'compare', 4, '["memory","compare"]', 1),
  ('idea-q-033', '如果可以带我去看一个和你过去有关的地方，你最想带我去哪？', 'memory', 'recommend', 3, '["memory","recommend"]', 1),
  ('idea-q-034', '你觉得哪些过去的经历，最明显地塑造了现在的你？', 'memory', 'explain', 4, '["memory","explain"]', 1),
  ('idea-q-035', '如果可以回到人生中的某一天旁观自己，你最想看哪一天？', 'memory', 'imagine', 4, '["memory","imagine"]', 1),
  ('idea-q-036', '如果能对某个过去的自己说一句话，你最想对几岁的自己说什么？', 'memory', 'hypothetical', 5, '["memory","hypothetical"]', 1),
  ('idea-q-037', '如果一年后有一个普通的星期三，你希望那时的生活大概是什么样？', 'future', 'imagine', 2, '["future","imagine"]', 1),
  ('idea-q-038', '你觉得未来一年自己最可能学会什么新东西？', 'future', 'predict', 2, '["future","predict"]', 1),
  ('idea-q-039', '你心里理想的“稳定生活”具体是什么样，而不是抽象地说稳定？', 'future', 'describe', 4, '["future","describe"]', 1),
  ('idea-q-040', '未来几年里，如果只能优先实现一件事：事业、学习、旅行、生活品质，你会先选什么？', 'future', 'choose', 3, '["future","choose"]', 1),
  ('idea-q-041', '你现在想要的未来，和三年前想象的未来有什么不同？', 'future', 'compare', 4, '["future","compare"]', 1),
  ('idea-q-042', '如果要给未来的我们留下一项固定仪式，你会推荐什么？', 'future', 'recommend', 3, '["future","recommend"]', 1),
  ('idea-q-043', '你做重要人生决定时，通常最看重安全感、兴趣、成长还是自由？为什么？', 'future', 'explain', 5, '["future","explain"]', 1),
  ('idea-q-044', '如果未来某个阶段我们的生活节奏差很多，你希望怎样保持彼此仍然在同一条线上？', 'future', 'hypothetical', 5, '["future","hypothetical"]', 1),
  ('idea-q-045', '什么样的工作状态会让你觉得自己今天过得很有价值？', 'work', 'describe', 3, '["work","describe"]', 1),
  ('idea-q-046', '对你来说，“做得好”和“做得开心”哪个更重要？它们冲突时你通常怎么选？', 'work', 'compare', 3, '["work","compare"]', 1),
  ('idea-q-047', '有没有一次工作或项目经历，让你第一次意识到自己其实很擅长某件事？', 'work', 'recall', 2, '["work","recall"]', 1),
  ('idea-q-048', '最近有没有一个提高工作效率的小方法，值得推荐给我？', 'work', 'recommend', 1, '["work","recommend"]', 1),
  ('idea-q-049', '如果收入完全不是问题，你还会保留现在工作里哪些部分，又会删掉哪些部分？', 'work', 'hypothetical', 4, '["work","hypothetical"]', 1),
  ('idea-q-050', '最近有没有一个你突然很想学会的小技能或知识？', 'study', 'describe', 1, '["study","describe"]', 1),
  ('idea-q-051', '学生时代有没有一门课或一个老师，真正改变过你看事情的方式？', 'study', 'recall', 3, '["study","recall"]', 1),
  ('idea-q-052', '你更喜欢自己慢慢研究，还是和别人讨论着学？为什么？', 'study', 'compare', 2, '["study","compare"]', 1),
  ('idea-q-053', '最近学到的一个有意思的小知识是什么？讲给我听听。', 'study', 'recommend', 1, '["study","recommend"]', 1),
  ('idea-q-054', '如果可以无压力地重新读一个完全不同的专业，你会选什么？', 'study', 'hypothetical', 3, '["study","hypothetical"]', 1),
  ('idea-q-055', '你觉得什么样的人最容易和你成为真正的朋友？', 'friends', 'describe', 2, '["friends","describe"]', 1),
  ('idea-q-056', '有没有一段友情里的小事，你到现在想起来还会觉得很温暖？', 'friends', 'recall', 3, '["friends","recall"]', 1),
  ('idea-q-057', '你觉得自己对朋友和对伴侣的依赖方式有什么不同？', 'friends', 'compare', 4, '["friends","compare"]', 1),
  ('idea-q-058', '当朋友和你价值观差很多时，什么情况下你仍然愿意保持亲近？', 'friends', 'explain', 4, '["friends","explain"]', 1),
  ('idea-q-059', '如果我要认识你的一位朋友，你最想先介绍谁？为什么？', 'friends', 'recommend', 2, '["friends","recommend"]', 1),
  ('idea-q-060', '如果一个很重要的朋友和我发生误会，你希望自己在中间扮演什么角色？', 'friends', 'hypothetical', 4, '["friends","hypothetical"]', 1),
  ('idea-q-061', '你觉得自己从家里带出来的一个最好习惯是什么？', 'family', 'describe', 3, '["family","describe"]', 1),
  ('idea-q-062', '有没有一道菜、一个节日或一个习惯，会让你很有“家”的感觉？', 'family', 'recall', 2, '["family","recall"]', 1),
  ('idea-q-063', '你希望未来自己的家庭氛围，和成长中的家庭有哪些相似或不同？', 'family', 'compare', 5, '["family","compare"]', 1),
  ('idea-q-064', '你觉得家人表达关心的方式里，哪些最容易被你感受到？', 'family', 'explain', 4, '["family","explain"]', 1),
  ('idea-q-065', '如果以后我们和各自家庭的期待发生冲突，你希望我们怎样站在彼此身边？', 'family', 'hypothetical', 5, '["family","hypothetical"]', 1),
  ('idea-q-066', '如果现在可以立刻拥有一只宠物，你最想养什么？会给它取什么名字？', 'pets', 'describe', 1, '["pets","describe"]', 1),
  ('idea-q-067', '小时候有没有遇到过一只让你印象特别深的动物？', 'pets', 'recall', 1, '["pets","recall"]', 1),
  ('idea-q-068', '如果我们以后养一只宠物，你觉得它最可能被谁宠坏？为什么？', 'pets', 'imagine', 1, '["pets","imagine"]', 1),
  ('idea-q-069', '如果家里只能让一种动物自由进出，你会选猫、狗、鸟还是别的？', 'pets', 'hypothetical', 2, '["pets","hypothetical"]', 1),
  ('idea-q-070', '如果现在送我们一张周末往返票，你最想推荐去哪里？', 'travel', 'recommend', 1, '["travel","recommend"]', 1),
  ('idea-q-071', '你最喜欢旅行里的哪一部分：出发、路上、抵达、乱逛还是回程？', 'travel', 'describe', 2, '["travel","describe"]', 1),
  ('idea-q-072', '过去哪一次旅行里，有一个很小但一直记得的瞬间？', 'travel', 'recall', 3, '["travel","recall"]', 1),
  ('idea-q-073', '你更喜欢把行程安排得很细，还是留很多空白临时决定？', 'travel', 'compare', 2, '["travel","compare"]', 1),
  ('idea-q-074', '如果让我们去一个完全陌生的城市住一个月，你希望每天怎么生活？', 'travel', 'imagine', 3, '["travel","imagine"]', 1),
  ('idea-q-075', '如果一次旅行中我们对节奏意见完全相反，你觉得怎样分配时间最舒服？', 'travel', 'hypothetical', 4, '["travel","hypothetical"]', 1),
  ('idea-q-076', '最近吃过最好吃的一样东西是什么？如果可以，现在就带我去吃。', 'food', 'recommend', 1, '["food","recommend"]', 1),
  ('idea-q-077', '有什么食物是你一吃就会明显心情变好的？', 'food', 'describe', 1, '["food","describe"]', 1),
  ('idea-q-078', '有没有一道食物和某个人、某个地方或某段时间牢牢绑在一起？', 'food', 'recall', 3, '["food","recall"]', 1),
  ('idea-q-079', '你更在意一顿饭好不好吃，还是一起吃饭的人和氛围？', 'food', 'compare', 2, '["food","compare"]', 1),
  ('idea-q-080', '如果今晚只能用冰箱里现有的东西给我们做一顿饭，你会想做什么？', 'food', 'imagine', 2, '["food","imagine"]', 1),
  ('idea-q-081', '如果以后每周固定有一天一起做饭，你希望它是什么风格？', 'food', 'hypothetical', 2, '["food","hypothetical"]', 1),
  ('idea-q-082', '有没有一本书、一个故事或一篇文章，你觉得我会喜欢？', 'literature', 'recommend', 1, '["literature","recommend"]', 1),
  ('idea-q-083', '你喜欢的文字通常有什么共同气质？', 'literature', 'describe', 2, '["literature","describe"]', 1),
  ('idea-q-084', '有没有一句书里的话，在你人生某个阶段真的陪过你？', 'literature', 'recall', 3, '["literature","recall"]', 1),
  ('idea-q-085', '如果我们可以一起进入一本书的世界生活一天，你会选哪一本？', 'literature', 'hypothetical', 3, '["literature","hypothetical"]', 1),
  ('idea-q-086', '如果今晚一起看一部电影，你现在最想选哪一部？', 'film', 'recommend', 1, '["film","recommend"]', 1),
  ('idea-q-087', '什么样的电影最容易让你看完以后还想很久？', 'film', 'describe', 2, '["film","describe"]', 1),
  ('idea-q-088', '你看电影更容易被故事、人物、画面还是音乐打动？', 'film', 'compare', 2, '["film","compare"]', 1),
  ('idea-q-089', '如果我们的生活被拍成电影，你觉得现在大概处在什么类型、什么段落？', 'film', 'hypothetical', 3, '["film","hypothetical"]', 1),
  ('idea-q-090', '最近有没有一首歌很想塞进我的耳机里？', 'music', 'recommend', 1, '["music","recommend"]', 1),
  ('idea-q-091', '有没有一首歌，只要前奏响起就会把你带回某段时间？', 'music', 'recall', 3, '["music","recall"]', 1),
  ('idea-q-092', '你最喜欢在什么场景下听歌？那时候你通常会选什么类型？', 'music', 'describe', 2, '["music","describe"]', 1),
  ('idea-q-093', '如果要给我们最近这段时间配一首背景音乐，你会选什么？', 'music', 'hypothetical', 3, '["music","hypothetical"]', 1),
  ('idea-q-094', '你玩游戏时最享受的是赢、探索、收集、社交还是沉浸故事？', 'games', 'describe', 1, '["games","describe"]', 1),
  ('idea-q-095', '小时候或学生时代有没有一款游戏，让你特别怀念？', 'games', 'recall', 1, '["games","recall"]', 1),
  ('idea-q-096', '你更喜欢一起合作通关，还是互相竞争？为什么？', 'games', 'compare', 3, '["games","compare"]', 1),
  ('idea-q-097', '如果现实生活突然变成游戏，你觉得自己的隐藏属性最高的是哪一项？', 'games', 'hypothetical', 2, '["games","hypothetical"]', 1),
  ('idea-q-098', '最近有没有一种颜色、材质或画面特别吸引你？', 'aesthetics', 'describe', 1, '["aesthetics","describe"]', 1),
  ('idea-q-099', '你更喜欢精致有秩序的空间，还是有生活痕迹、稍微乱一点的空间？', 'aesthetics', 'compare', 2, '["aesthetics","compare"]', 1),
  ('idea-q-100', '如果让我换一个手机壁纸风格，你会给我推荐什么？', 'aesthetics', 'recommend', 1, '["aesthetics","recommend"]', 1),
  ('idea-q-101', '你觉得自己的审美里，有哪些部分其实和性格很像？', 'aesthetics', 'explain', 4, '["aesthetics","explain"]', 1),
  ('idea-q-102', '如果让你设计一个只属于我们的房间，你最想先决定哪三个细节？', 'aesthetics', 'imagine', 3, '["aesthetics","imagine"]', 1),
  ('idea-q-103', '如果今天晚上我们可以瞬间移动到世界上任何一个地方待两小时，你会选哪里？', 'imagination', 'imagine', 1, '["imagination","imagine"]', 1),
  ('idea-q-104', '如果你突然拥有一种没什么大用但很好玩的超能力，你想要什么？', 'imagination', 'hypothetical', 1, '["imagination","hypothetical"]', 1),
  ('idea-q-105', '如果可以体验一天别人的生活，你更想选历史人物、虚构角色还是陌生普通人？', 'imagination', 'choose', 2, '["imagination","choose"]', 1),
  ('idea-q-106', '如果未来家里真的有一个很聪明的机器人，你觉得我们最先让它帮忙做什么？', 'imagination', 'predict', 2, '["imagination","predict"]', 1),
  ('idea-q-107', '如果你的内心世界是一颗星球，它现在的地貌、天气和居民会是什么样？', 'imagination', 'describe', 3, '["imagination","describe"]', 1),
  ('idea-q-108', '如果我们能提前看到十年后的某一个普通片段，你最想看到什么，而不是知道什么答案？', 'imagination', 'hypothetical', 4, '["imagination","hypothetical"]', 1);
